version: "3"

services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - 16686:16686 # internal port of jaeger UI
      # - 6837

  db:
    image: postgres:latest
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "root"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s
    environment:
      - POSTGRES_HOST_AUTH_METHOD=md5
      - POSTGRES_INITDB_ARGS=--auth-host=md5
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
      - PGDATA=/var/lib/postgresql/data/pgdata

  migrations:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile-migrations

  migrations-shard:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile-shard

  srv:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile-service
    restart: always
