version: "3"

services:
  db-marketplace:
    network_mode: host
    image: postgres:latest
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "root"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - data:/var/lib/postgresql/data

  migrations-marketplace:
    network_mode: host
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile-migrations
      args:
        service: service-marketplace
    depends_on:
      db-marketplace:
        condition: service_healthy

  srv-marketplace:
    network_mode: host
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile-service
      args:
        service: service-marketplace
    restart: always
    depends_on:
      - migrations-marketplace

volumes:
  data:
    driver: local
