version: "3"

services:
  prometheus:
    extends:
      file: base.yml
      service: prometheus
    ports:
      - 2112
    networks:
      - marketplace-network

  jaeger:
    extends:
      file: base.yml
      service: jaeger
    networks:
      - marketplace-network

  db:
    extends:
      file: base.yml
      service: db
    ports:
      - 5432 # port of postgres
    volumes:
      - marketplace-data:/var/lib/postgresql/data
    networks:
      - marketplace-network

  migrations:
    extends:
      file: base.yml
      service: migrations
    build:
      args:
        service: service-marketplace
    networks:
      - marketplace-network
    depends_on:
      db:
        condition: service_healthy

  srv:
    ports:
      - 8080 # internal port of grpc service
      - 2112:2112 # metrics port
    extends:
      file: base.yml
      service: srv
    networks:
      - marketplace-network
    build:
      args:
        service: service-marketplace
    depends_on:
      - migrations

networks:
  marketplace-network:

volumes:
  marketplace-data:
    driver: local
