version: "3"

services:
  db:
    extends:
      file: base.yml
      service: db
    ports:
      - 5432
    volumes:
      - marketplace-data:/var/lib/postgresql/data
    networks:
      - marketplace-network

  migrations:
    extends:
      file: base.yml
      service: migrations
    build:
      args:
        service: service-marketplace
    networks:
      - marketplace-network
    depends_on:
      db:
        condition: service_healthy

  srv:
    ports:
      - 8080
      - 2112
    extends:
      file: base.yml
      service: srv
    networks:
      - marketplace-network
    build:
      args:
        service: service-marketplace
    depends_on:
      - migrations

networks:
  marketplace-network:

volumes:
  marketplace-data:
    driver: local
