version: "3"

services:
  prometheus:
    network_mode: host
    image: prom/prometheus
    volumes:
      - /home/leo/route256/homework-3/prometheus.yml:/etc/prometheus/prometheus.yml:ro

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - 16686:16686
      - 6831:6831/udp
