FROM golang:1.17-alpine AS builder


WORKDIR /app

ADD . .
RUN go mod download

FROM builder AS build-srv

# name of service
ARG service

RUN go build -o service cmd/${service}/main.go
CMD ["./service"]
