FROM gomicro/goose

# name of service
ARG service

RUN echo "Oh dang look at that service: ${service}"

ADD /internal/${service}/migrations/ /migrations/

RUN chmod +x /migrations/entrypoint.sh

ENTRYPOINT ["/migrations/entrypoint.sh"]