service:
  name: service-orders
database:
  url: postgresql://root:root@db-orders:5432/root
server:
  url: srv-orders:8080
metrics:
  prometheus-url: srv-orders:2112
  jaeger-url: jaeger:6831

clients:
  marketplace:
    url: srv-marketplace:8080
    timeout-ms: 100
  warehouse:
    url: srv-warehouse:8080
    timeout-ms: 100

saga:
  retries: 5
  timeout-ms: 10000
